[[redirects]]
  from = "/waternow/*"
  to = "https://www.waternow.go.kr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://me.go.kr/:splat"
  status = 200
  force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200